BROKER_IP = "127.0.0.1"  
PORT = 1883 # port du serveur mosquitto
TOPIC_BRAS1 = "bras1/ready"
TOPIC_BRAS2 = "bras2/ready"
TOPIC_BRAS3 = "bras3/ready"
TOPIC_BRAS4 = "bras4/ready"
TOPIC_CONV2 = "convoyeur2/start"
TOPIC_CONV3 = "convoyeur3/start"
TOPIC_CONV4 = "convoyeur4/start"
